name: Build images
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "The version of the image to build. This appears to be in timestamp format."
env:
  IMAGE_NAME: minio

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/minio
    steps:
      - uses: actions/checkout@v2
      - name: Run the workflow
        run: docker build --platform linux/amd64,linux/arm64,windows/amd64 --build-arg VERSION=$VERSION -t ${IMAGE_NAME} .
      - name: Push image to github container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: |
          docker push ${IMAGE_NAME}:latest
          docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:$VERSION
          docker push ${IMAGE_NAME}:$VERSION
