name: Build images
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "The version of the image to build. This appears to be in timestamp format."
env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build:
    strategy:
      matrix:
        OS: [linux, windows]
        ARCH: [amd64, arm64]
        exclude:
          - OS: windows
            ARCH: arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login github container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run the workflow
        env:
          OS: ${{ matrix.OS }}
          ARCH: ${{ matrix.ARCH }}
          VERSION: ${{ env.VERSION }}
        run: docker buildx bake
